services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  ipfs:
    image: ipfs/go-ipfs:latest
    container_name: ipfs-node
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8070:8070"
    volumes:
      - ipfs_data:/data/ipfs
      - ipfs_staging:/export

  springboot-app:
    build: .
    container_name: springboot-app
    ports:
      - "8086:8085"
    depends_on:
      - broker
      - ipfs
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - IPFS_NODE_HOST=ipfs-node
      - IPFS_NODE_PORT=5001
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=broker:29092
    restart: on-failure

volumes:
  ipfs_data:
  ipfs_staging:
