version: '3.8'
services:
  app:
    image: doctor-microservice
    container_name: doctor-app
    ports:
      - "8081:8080"
    depends_on:
      - kafka
    environment: # Make sure these match your .env file
      - DATABASE_URL=jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres
      - DATABASE_USERNAME=postgres.sbihxmjllrogpwipwrbq
      - DATABASE_PASSWORD=fJFCrWYnEPLNpVoE
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    restart: always
    networks:
      - app-network
  # ... (Kafka and Zookeeper remain mostly the same, but ensure they are on app-network)
  kafka:
    image: bitnami/kafka:3.7
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092 # Change this
      ALLOW_PLAINTEXT_LISTENER: yes
    depends_on:
      - zookeeper
    networks:
      - app-network
  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    networks:
      - app-network
networks:
  app-network:
    driver: bridge