# version: "3.8"

# services:
#   # zookeeper:
#   #   image: confluentinc/cp-zookeeper:7.5.0
#   #   ports:
#   #     - "2181:2181"

#   zookeeper:
#   image: confluentinc/cp-zookeeper:7.5.0
#   container_name: notification-zookeeper
#   ports:
#     - "2181:2181"
#   environment:
#     ZOOKEEPER_CLIENT_PORT: 2181       # ✅ This line is required
#     ZOOKEEPER_TICK_TIME: 2000


#   kafka:
#     image: confluentinc/cp-kafka:7.5.0
#     ports:
#       - "9092:9092"
#     environment:
#       KAFKA_BROKER_ID: 1
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#     depends_on:
#       - zookeeper

#   springboot:
#     build: ./emailproducer
#     ports:
#       - "8080:8080"
#     depends_on:
#       - kafka

#   fastapi:
#     build:
#       context: ./notification_service
#       dockerfile: Dockerfile
#     depends_on:
#       - kafka


version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    # container_name: notification-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: bitnami/kafka:3.5
    # container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper


  springboot:
    # container_name: notification-springboot
    build:
      context: ./emailproducer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  fastapi:
    # container_name: notification-fastapi
    build:
      context: ./notification_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - kafka
